# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               sky
tagline:             'blog'
description:         ''
url:                 https://sky25o5.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Lee KyungJu
  url:               https://sky25o5.github.io
  email:             kyungju2505@gmail.com

# Custom vars
version:             1.0.0
